export const ScreenNames = {
    DrawerNavigator:'DrawerNavigator',
    ContactDistributor:"ContactDistributor",
    UserOrders:"UserOrders",
    UserProfile: 'UserProfile',
    StartUpDrawer: "StartUpDrawer",
    CategoryItem: "CategoryItem",
    CategoryDetails: "CategoryDetails",
    ExecutiveManagementTeam: "ExecutiveManagementTeam",
    ModalScreens: "ModalScreens",
    AboutUsReadMoreModal: "AboutUsReadMoreModal",
    AboutUs: "AboutUs",
    MeetTheFounder: "MeetTheFounder",
    ContactUs: "ContactUs",
    SelectYourCountry:"SelectYourCountry",
    MakeSenseFoundation: "MakeSenseFoundation",
    FindADistributor:"FindADistributor",
    StartABusiness:"StartABusiness",
    SearchScreen: "SearchScreen",
    FilterDrawerItems: "FilterDrawerItems",
    ListOfStacks: "ListOfStacks",
    Press: "Press",
    TermsAndConditions:"TermsAndConditions",
    ShowCartScreen: "ShowCartScreen",
    CopyrightDMCAPolicy:"CopyrightDMCAPolicy",
    MainShoppingCartBag:"MainShoppingCartBag",
    FAQS: "FAQS",
    Careers:"Careers",
    AllProducts: "AllProducts",
    OrderConfirmation:"OrderConfirmation",
    Error_404:"Error_404",
    Error_503:"Error_503",
    Checkout_As_A_Guest:"Checkout_As_A_Guest",
    DistributorEnrollment:"DistributorEnrollment"
}