export const ScreenNames = {
    StartUpDrawer: "StartUpDrawer",
    CategoryItem: "CategoryItem",
    CategoryDetails: "CategoryDetails",
    ExecutiveManagementTeam: "ExecutiveManagementTeam",
    ModalScreens: "ModalScreens",
    AboutUsReadMoreModal: "AboutUsReadMoreModal",
    AboutUs: "AboutUs",
    MeetTheFounder: "MeetTheFounder",
    ContactUs: "ContactUs",
    SelectYourCountry:"SelectYourCountry",
    MakeSenseFoundation: "MakeSenseFoundation",
    FindADistributor:"FindADistributor",
    StartABusiness:"StartABusiness",
    SearchScreen: "SearchScreen",
    FilterDrawerItems: "FilterDrawerItems",
    ListOfStacks: "ListOfStacks",
    Press: "Press",
    TermsAndConditions:"TermsAndConditions",
    ShowCartScreen: "ShowCartScreen",
    CopyrightDMCAPolicy:"CopyrightDMCAPolicy",
    MainShoppingCartBag:"MainShoppingCartBag"
}